import { describe, it, expect } from "vitest";
import {
  buildResultPublishedActionPath,
  buildAbsoluteResultLink,
  validateStoredActionPath,
} from "./actionLink.js";

// P5-N1-I2 Slice 1 — action-link builder + render-time combiner.
//
// P5-N1-R0 §16 — frozen: the V1 builder is command-specific and trusted,
// NOT a generic whitelist framework. The builder returns the real existing
// candidate result route /exam/:attemptId/result (navigation by attemptId,
// not examId). The render-time combiner prepends PUBLIC_WEB_ORIGIN only at
// email-render time, after re-validating the stored path.

describe("buildResultPublishedActionPath", () => {
  it("returns the canonical /exam/:attemptId/result route", () => {
    const path = buildResultPublishedActionPath(
      "00000000-0000-4000-8000-00000000000a",
    );
    expect(path).toBe("/exam/00000000-0000-4000-8000-00000000000a/result");
  });

  it("rejects an empty attemptId", () => {
    expect(() => buildResultPublishedActionPath("")).toThrow();
  });

  it("rejects a non-string attemptId", () => {
    expect(() =>
      buildResultPublishedActionPath(null as unknown as string),
    ).toThrow();
  });

  it("produces a path accepted by the contract validator", () => {
    // Round-trip: the builder output must always pass render-time validation.
    const path = buildResultPublishedActionPath(
      "00000000-0000-4000-8000-00000000000a",
    );
    expect(validateStoredActionPath(path)).toBe(true);
  });
});

describe("validateStoredActionPath (render-time re-validation)", () => {
  // The stored actionPath is server-generated by a trusted builder, but the
  // render-time combiner re-validates before prepending PUBLIC_WEB_ORIGIN so
  // a tampered/legacy row can never produce an off-site Email link.

  it("accepts a canonical result path", () => {
    expect(
      validateStoredActionPath(
        "/exam/00000000-0000-4000-8000-00000000000a/result",
      ),
    ).toBe(true);
  });

  it("accepts null (non-actionable notification)", () => {
    expect(validateStoredActionPath(null)).toBe(true);
  });

  it("rejects an external URL", () => {
    expect(validateStoredActionPath("https://evil.example/exam/x/result")).toBe(
      false,
    );
  });

  it("rejects a protocol-relative URL", () => {
    expect(validateStoredActionPath("//evil.example/exam/x/result")).toBe(
      false,
    );
  });

  it("rejects dot-dot traversal", () => {
    expect(validateStoredActionPath("/exam/../admin/users/result")).toBe(false);
  });

  it("rejects percent-encoded traversal", () => {
    expect(validateStoredActionPath("/exam/%2e%2e/admin/result")).toBe(false);
  });

  it("rejects a backslash", () => {
    expect(validateStoredActionPath("/exam/x\\result")).toBe(false);
  });

  it("rejects a control character", () => {
    expect(validateStoredActionPath("/exam/x/result\n")).toBe(false);
  });

  it("rejects an unknown route prefix", () => {
    expect(validateStoredActionPath("/admin/exams/123")).toBe(false);
  });
});

describe("buildAbsoluteResultLink (PUBLIC_WEB_ORIGIN combiner)", () => {
  it("combines a validated site-relative path with PUBLIC_WEB_ORIGIN", () => {
    const url = buildAbsoluteResultLink(
      "/exam/00000000-0000-4000-8000-00000000000a/result",
      "https://exam.example.local",
    );
    expect(url).toBe(
      "https://exam.example.local/exam/00000000-0000-4000-8000-00000000000a/result",
    );
  });

  it("strips a trailing slash from PUBLIC_WEB_ORIGIN", () => {
    const url = buildAbsoluteResultLink(
      "/exam/x/result",
      "https://exam.example.local/",
    );
    expect(url).toBe("https://exam.example.local/exam/x/result");
  });

  it("rejects an invalid stored path before combining (no off-site link)", () => {
    expect(() =>
      buildAbsoluteResultLink("//evil.example/x", "https://exam.example.local"),
    ).toThrow(/invalid action path/i);
  });

  it("rejects a non-absolute PUBLIC_WEB_ORIGIN", () => {
    expect(() =>
      buildAbsoluteResultLink("/exam/x/result", "exam.example.local"),
    ).toThrow(/PUBLIC_WEB_ORIGIN/);
  });
});
