export const routes = {
  login: "/login",
  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    candidates: "/admin/candidates",
    settings: "/admin/settings",
    candidateFields: "/admin/candidate-fields",
    courses: "/admin/courses",
    questions: "/admin/questions",
    questionsNew: "/admin/questions/new",
    questionEdit: (id: string) => `/admin/questions/${id}/edit`,
    questionsImport: "/admin/questions/import",
    exams: "/admin/exams",
    examsNew: "/admin/exams/new",
    examDetail: (id: string) => `/admin/exams/${id}`,
    examScores: (id: string) => `/admin/exams/${id}/scores`,
    results: "/admin/results",
    attemptDetail: (id: string) => `/admin/attempts/${id}`,
    system: "/admin/system",
  },
  exam: {
    list: "/exam/list",
    start: (id: string) => `/exam/${id}/start`,
    take: (id: string) => `/exam/${id}/take`,
    result: (id: string) => `/exam/${id}/result`,
  },
} as const;
