/** Centralized route path constants and path-builder functions. */
export const routes = {
  login: "/login",
  launchpad: "/launchpad",
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    candidates: "/admin/candidates",
    settings: "/admin/settings",
    candidateFields: "/admin/candidate-fields",
    courses: "/admin/courses",
    questions: "/admin/questions",
    questionsNew: "/admin/questions/new",
    questionEdit: (id: string) => `/admin/questions/${id}/edit`,
    questionsImport: "/admin/questions/import",
    exams: "/admin/exams",
    examsNew: "/admin/exams/new",
    examDetail: (id: string) => `/admin/exams/${id}`,
    examEdit: (id: string) => `/admin/exams/${id}/edit`,
    examScores: (id: string) => `/admin/exams/${id}/scores`,
    examProfiles: "/admin/exam-profiles",
    examProfileNew: "/admin/exam-profiles/new",
    examProfileEdit: (id: string) => `/admin/exam-profiles/${id}/edit`,
    examProctor: (id: string) => `/admin/exams/${id}/proctor`,
    examProctorMonitor: (id: string) => `/admin/exams/${id}/proctor/monitor`,
    proctorWorkspace: "/admin/proctor",
    results: "/admin/results",
    gradingQueue: "/admin/grading-queue",
    gradingDetail: (id: string) => `/admin/grading-queue/${id}`,
    auditLogs: "/admin/audit-logs",
    importLogs: "/admin/import-logs",
    attemptDetail: (id: string) => `/admin/attempts/${id}`,
    recovery: "/admin/recovery",
    recoveryIncident: (id: string) => `/admin/recovery/incidents/${id}`,
    recoveryAttempt: (id: string) => `/admin/recovery/attempts/${id}`,
    recoveryExam: (id: string) => `/admin/recovery/exams/${id}`,
    system: "/admin/system",
    diagnostics: "/admin/system",
  },
  exam: {
    list: "/exam/list",
    start: (id: string) => `/exam/${id}/start`,
    take: (id: string) => `/exam/${id}/take`,
    result: (id: string) => `/exam/${id}/result`,
    settings: "/exam/settings",
  },
} as const;
